/* tslint:disable */
/* eslint-disable */
/**
 * GAIA-X Federated Catalogue
 * This is the REST API of the Gaia-X catalogue.
 *
 * The version of the OpenAPI document: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

